### PR TITLE
QtWebKitWidgets is no longer available

### PR DESCRIPTION
**Pull request by kikislater**
QtWebKitWidgets is no longer available
http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html

### CODE REVIEW

**Comment by Guts** [comment]
Hi @kikislater ,

Thanks for your interest and PR!

Can you fix the [linter error](https://results.pre-commit.ci/run/github/342655053/1668507044.30V8YajfTnmah7HHrMtudQ) please?

Does this change affect compatible QGIS versions?

**Comment by kikislater** [comment]
Please wait, could be distribution specific case ...
https://github.com/qgis/QGIS/issues/33924
https://github.com/archlinux/svntogit-community/commit/783d52696588264257eed9d32c9fd212d0fdeace

**Comment by Guts** [comment]
So, what should we do?

@lbartoletti any idea?

**Comment by kikislater** [comment]
Asking Qgis dev's again about QtWebkit (and its pyQt module) is the best IMO
It was removed from Archlinux and may be soon in others platforms (security concern) : 
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=qtwebkit&product=Fedora&product=Fedora+EPEL

**Review by lbartoletti — APPROVED** [review]

**Comment by kikislater** [comment]
@Guts @lbartoletti So I haven't followed the behaviour of qtwebkit in Qgis, what will happen to qtwebkit in Qgis, will it still be needed? I've come to understand that removing it would cause problems with Qgis 3D, which needs qtwebkit, so if you have any more info, please let me know!

**Pull request merged**
